### ISSUE TITLE
Not able to watermark 'text' due to font error

### ISSUE THREAD

**Issue by viv1ag** [bhaskar4n/watermarker#1]
Hi Bhaskar,

Thank you for this python script.
While I was trying to execute this; I am getting Font related error. Please see below whole python shell log:

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========= RESTART: C:\Vivek_Personal\watermarker-master\watermark.py =========
1. Text only
2. Logo only
3. Both text and logo
choose (1 or 2 or 3) : 1
enter water_marker text: papertreasure
enter the text size(default=72): 50
Transparent level(default=100): 50
images/13891885_942077929272343_7101195289443155621_n.jpg
(720, 960)

Traceback (most recent call last):
  File "C:\Vivek_Personal\watermarker-master\watermark.py", line 53, in <module>
    font = ImageFont.truetype("Arial.ttf",txtsize)
  File "C:\Python27\lib\site-packages\PIL\ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "C:\Python27\lib\site-packages\PIL\ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource
>>> 
```

However, I was able to watermark logo successfully.
Kindly help here.

regards,
Vivek Agarwal

**Comment by bhaskar4n** [comment]
if you are using Linux system. please replace the "**font = ImageFont.truetype("Arial.ttf",txtsize)**" to 
**font = ImageFont.truetype("/usr/share/fonts/truetype/droid/DroidSansMono.ttf",txtsize)**

In Linux operating system, the font file(DroidSansMono.ttf) will located at /usr/share/fonts/truetype/droid/DroidSansMono.ttf. so mention this address location.

**Comment by viv1ag** [comment]
I got the root cause! On my window OS; font name is "arial.ttf" not "Arial.ttf". So after changing font name, I got the correct result. :-)
Do like this: `font = ImageFont.truetype("Arial.ttf",txtsize)`

**Comment by bhaskar4n** [comment]
@thank you for identifying this error.   i corrected this error in my python script
